echo off cd ChangeBMP

FE *.BMP "BMPIMG %% /I"

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\KB\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\TK\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\WC\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\KB\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\TK\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\WC\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\KB\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\TK\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\WC\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\AN\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CN\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\CY\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\KB\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\MO\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PN\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\SI\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\TK\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\CM\WC\*.db


del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\PU\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\PU\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\PU\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\DE\PU\*.db


del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\SI\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\PU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MSG\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\PU\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\SI\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\PU\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MSG\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\PU\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\SI\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\PU\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MSG\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\PU\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CM\SI\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\CY\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MO\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SE\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\SI\PU\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\MSG\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AM\TM\PU\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\BT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\IM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\PU\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\BT\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\IM\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\PU\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\BT\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\IM\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\PU\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\BT\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\IM\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\AW\PU\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH1\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\CH2\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\DEU\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ENG\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MSG\*.jbf

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MSG\*.db


del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\ERR\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\LN\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MD\*.scc
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MSG\*.scc

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\ERR\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\LN\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MD\*.bmp
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MSG\*.bmp

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\ERR\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\LN\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MD\*.jbf
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MSG\*.jbf


del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ESP\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\FRA\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\IDN\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\ITA\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\JPN\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\KOR\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\PRT\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\RUS\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\TUR\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL1\VNM\MSG\*.db

del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\ERR\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\LN\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MD\*.db
del C:\Project5\root\MakeBIN_MAIN\ChangeBMP\change\MAINL2\MSG\*.db

