echo F|xcopy .\BMP\LAN\MAINL1\CH1\MD\K202.bmp .\copyfl\LAN\MAINL1\CH1\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\CH2\MD\K202.bmp .\copyfl\LAN\MAINL1\CH2\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\DEU\MD\K202.bmp .\copyfl\LAN\MAINL1\DEU\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ENG\MD\K202.bmp .\copyfl\LAN\MAINL1\ENG\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ESP\MD\K202.bmp .\copyfl\LAN\MAINL1\ESP\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\FRA\MD\K202.bmp .\copyfl\LAN\MAINL1\FRA\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\IDN\MD\K202.bmp .\copyfl\LAN\MAINL1\IDN\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ITA\MD\K202.bmp .\copyfl\LAN\MAINL1\ITA\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\JPN\MD\K202.bmp .\copyfl\LAN\MAINL1\JPN\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\KOR\MD\K202.bmp .\copyfl\LAN\MAINL1\KOR\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\PRT\MD\K202.bmp .\copyfl\LAN\MAINL1\PRT\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\RUS\MD\K202.bmp .\copyfl\LAN\MAINL1\RUS\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\TUR\MD\K202.bmp .\copyfl\LAN\MAINL1\TUR\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\VNM\MD\K202.bmp .\copyfl\LAN\MAINL1\VNM\MD\K202.bmp 
echo F|xcopy .\BMP\LAN\MAINL2\MD\K202.bmp	      .\copyfl\LAN\MAINL2\MD\K202.bmp
echo F|xcopy .\BMP\LAN\MAINL1\CH1\MD\K203.bmp .\copyfl\LAN\MAINL1\CH1\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\CH2\MD\K203.bmp .\copyfl\LAN\MAINL1\CH2\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\DEU\MD\K203.bmp .\copyfl\LAN\MAINL1\DEU\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ENG\MD\K203.bmp .\copyfl\LAN\MAINL1\ENG\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ESP\MD\K203.bmp .\copyfl\LAN\MAINL1\ESP\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\FRA\MD\K203.bmp .\copyfl\LAN\MAINL1\FRA\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\IDN\MD\K203.bmp .\copyfl\LAN\MAINL1\IDN\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ITA\MD\K203.bmp .\copyfl\LAN\MAINL1\ITA\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\JPN\MD\K203.bmp .\copyfl\LAN\MAINL1\JPN\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\KOR\MD\K203.bmp .\copyfl\LAN\MAINL1\KOR\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\PRT\MD\K203.bmp .\copyfl\LAN\MAINL1\PRT\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\RUS\MD\K203.bmp .\copyfl\LAN\MAINL1\RUS\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\TUR\MD\K203.bmp .\copyfl\LAN\MAINL1\TUR\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\VNM\MD\K203.bmp .\copyfl\LAN\MAINL1\VNM\MD\K203.bmp 
echo F|xcopy .\BMP\LAN\MAINL2\MD\K203.bmp	      .\copyfl\LAN\MAINL2\MD\K203.bmp
echo F|xcopy .\BMP\LAN\MAINL1\CH1\MD\K411.bmp .\copyfl\LAN\MAINL1\CH1\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\CH2\MD\K411.bmp .\copyfl\LAN\MAINL1\CH2\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\DEU\MD\K411.bmp .\copyfl\LAN\MAINL1\DEU\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ENG\MD\K411.bmp .\copyfl\LAN\MAINL1\ENG\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ESP\MD\K411.bmp .\copyfl\LAN\MAINL1\ESP\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\FRA\MD\K411.bmp .\copyfl\LAN\MAINL1\FRA\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\IDN\MD\K411.bmp .\copyfl\LAN\MAINL1\IDN\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ITA\MD\K411.bmp .\copyfl\LAN\MAINL1\ITA\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\JPN\MD\K411.bmp .\copyfl\LAN\MAINL1\JPN\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\KOR\MD\K411.bmp .\copyfl\LAN\MAINL1\KOR\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\PRT\MD\K411.bmp .\copyfl\LAN\MAINL1\PRT\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\RUS\MD\K411.bmp .\copyfl\LAN\MAINL1\RUS\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\TUR\MD\K411.bmp .\copyfl\LAN\MAINL1\TUR\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\VNM\MD\K411.bmp .\copyfl\LAN\MAINL1\VNM\MD\K411.bmp 
echo F|xcopy .\BMP\LAN\MAINL2\MD\K411.bmp	      .\copyfl\LAN\MAINL2\MD\K411.bmp
echo F|xcopy .\BMP\LAN\MAINL1\CH1\MD\K412.bmp .\copyfl\LAN\MAINL1\CH1\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\CH2\MD\K412.bmp .\copyfl\LAN\MAINL1\CH2\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\DEU\MD\K412.bmp .\copyfl\LAN\MAINL1\DEU\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ENG\MD\K412.bmp .\copyfl\LAN\MAINL1\ENG\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ESP\MD\K412.bmp .\copyfl\LAN\MAINL1\ESP\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\FRA\MD\K412.bmp .\copyfl\LAN\MAINL1\FRA\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\IDN\MD\K412.bmp .\copyfl\LAN\MAINL1\IDN\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\ITA\MD\K412.bmp .\copyfl\LAN\MAINL1\ITA\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\JPN\MD\K412.bmp .\copyfl\LAN\MAINL1\JPN\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\KOR\MD\K412.bmp .\copyfl\LAN\MAINL1\KOR\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\PRT\MD\K412.bmp .\copyfl\LAN\MAINL1\PRT\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\RUS\MD\K412.bmp .\copyfl\LAN\MAINL1\RUS\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\TUR\MD\K412.bmp .\copyfl\LAN\MAINL1\TUR\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL1\VNM\MD\K412.bmp .\copyfl\LAN\MAINL1\VNM\MD\K412.bmp 
echo F|xcopy .\BMP\LAN\MAINL2\MD\K412.bmp	      .\copyfl\LAN\MAINL2\MD\K412.bmp
