echo off cd ChangeBMP

FE *.BMP "BMPIMG %% /I"

cd change

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\BT\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\IM\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JB\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JI\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\KB\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\PU\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\TK\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\BT\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\IM\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\PU\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\BT\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\PU\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\BT\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\IM\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JB\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JI\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\KB\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\PU\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\TK\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\BT\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\IM\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\PU\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\BT\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\PU\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\BT\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\IM\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JB\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JI\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\KB\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\PU\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\TK\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\ERR\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\BT\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\IM\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\PU\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MSG\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\BT\*.jbf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\PU\*.jbf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\BT\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\IM\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JB\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\JI\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\KB\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\PU\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\CM\TK\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\BT\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\IM\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MO\PU\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\BT\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\SE\PU\*.db


del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH1\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\CH2\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\DEU\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ENG\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ESP\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\FRA\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\IDN\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\ITA\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\JPN\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\KOR\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\PRT\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\RUS\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\TUR\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL1\VNM\WK\*.db

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\ERR\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\LN\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MD\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MSG\*.scc
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\WK\*.scc

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\ERR\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\LN\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MD\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MSG\*.bmp
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\WK\*.bmp

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\ERR\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\LN\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MD\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MSG\*.jpf
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\WK\*.jpf

del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\ERR\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\LN\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MD\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\MSG\*.db
del C:\project5\root\MakeBIN_JOG\ChangeBMP\change\JOGL2\WK\*.db
